name: Tupelo Documentation
title: Tupelo Documentation
author: icarusz
email: andrew@quorumcontrol.com
description: Basic generated Jekyll site to enable a good developer onboarding experience
github_username: icarusz

markdown: kramdown
theme: just-the-docs
