# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tupelo Documentation
email: andrew@quorumcontrol.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the documentation site for Tupelo.  Tupelo is a new DLT (Distributed
  Ledger) focused on modeling "things" be they real world or virtual.
  The team is focused on practical applications of blockchain technology
  and providing a platform which provide developers joy.
baseurl: "https://docs.quorumcontrol.com" # the subpath of your site, e.g. /blog
# url: "http://www.quorumcontrol.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: icarusz
github_username:  icarusz


# Build settings
search_enabled: true
markdown: kramdown
aux_links:
  "Main Tupelo Website":
    - "http://www.quorumcontrol.com"
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs # this works locally but not when pushed
plugins:
  - jekyll-feed



# "Tupelo on Github""
#    - "https://github.com/quorumcontrol"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
